require "../../values/booleans.k"
require "../../values/integers.k"
require "../../values/streams.k"
require "../../values/strings.k"
require "../../values/types.k"
require "../../values/values.k"
require "../../values/variables.k"

module CINF-STATEMENTS-VALUES
  imports BOOLEANS
  imports INTEGERS
  imports STREAMS
  imports STRINGS
  imports TYPES
  imports VALUES
  imports VARIABLES
endmodule
